name: Jobs Dependent

on:
  push:
    branches:
      - main

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: stepA
        run: echo "Worldy"

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        run: echo "Hellojp"


